<div class="paginaReservas">

    <h1 class="title-page">Reservas</h1>
    <p class="description-page">Controla y administra todas las reservas del día</p>

    <div class="date-selector">

        <label>Fecha seleccionada:</label>
        <div class="calendar-container">
            <div class="calendar-trigger" id="calendarTrigger">
                <span class="calendar-icon">📅</span>
                <?php
                $formatter = new IntlDateFormatter(
                    'es_ES',
                    IntlDateFormatter::LONG,
                    IntlDateFormatter::NONE,
                    'Europe/Madrid',
                    IntlDateFormatter::GREGORIAN
                );
                ?>

                <span id="selectedDate"><?= $formatter->format(new DateTime()) ?></span>
            </div>

            <div class="mini-calendar" id="miniCalendar">
                <div class="calendar-header">
                    <h4 id="calendarMonth">Febrero 2026</h4>
                    <div class="calendar-nav">
                        <button class="calendar-nav-btn" id="prevMonth">◀</button>
                        <button class="calendar-nav-btn" id="nextMonth">▶</button>
                    </div>
                </div>

                <div class="calendar-weekdays">
                    <div class="calendar-weekday">L</div>
                    <div class="calendar-weekday">M</div>
                    <div class="calendar-weekday">X</div>
                    <div class="calendar-weekday">J</div>
                    <div class="calendar-weekday">V</div>
                    <div class="calendar-weekday">S</div>
                    <div class="calendar-weekday">D</div>
                </div>

                <div class="calendar-days" id="calendarDays">
                    <!-- Days will be generated by JavaScript -->
                </div>
            </div>
        </div>

        <div class="stats-summary">
            <div class="stat-card">
                <div class="stat-number stat-total"><?= count($reservas) ?></div>
                <div class="stat-label">Total reservas</div>
            </div>
            <div class="stat-card">
                <div class="stat-number stat-confirmadas"><?= count(array_filter($reservas, function ($reserva) {
                                                return intval($reserva["pagadas"]) === 1;
                                            })); ?></div>
                <div class="stat-label">Confirmadas</div>
            </div>
            <div class="stat-card">
                <div class="stat-number stat-no-confirmadas"><?= count(array_filter($reservas, function ($reserva) {
                                                return intval($reserva["pagadas"]) === 0;
                                            })); ?></div>
                <div class="stat-label">Pendientes</div>
            </div>
        </div>


    </div>

    <h1 class="title-page">Reservas de instalaciones</h1>
    <div class="contenedor-reservas">
        <?php if (isset($reservas) && count($reservas) > 0) : ?>
        

            <?php foreach ($reservas as $reserva) : ?>
                <div class="card-reserva" data-index="<?= $reserva["id_reserva"] ?>" data-pedido="<?= $reserva["id_pedido"] ?>" data-tipo="<?= $reserva["tipo_reserva"] ?>">
                    <div class="contenedor-img-reserva" style="background-image: url('<?= base_url() ?>images/<?= $reserva["imagen1"] ?>');"></div>
                    <div class="contenedor-card-reserva">
                        <span class="categoria-instalacion-reserva"><?= $reserva["categoria"] ?></span>
                        <h1 class="title-pista-reserva"><?= $reserva["nombre_pista"] ?></h1>
                        <p class="instalacionDireccion"><?= $reserva["nombre_instalacion"] ?> · <?= $reserva["direccion"] ?></p>

                        <div class="contenedor-usuario">
                            <div class="logo-img"><?= mb_strtoupper(mb_substr($reserva["nombre_usuario"], 0, 1, 'UTF-8')); ?></div>
                            <div class="informacion-usuario">
                                <p class="nombre-usuario"><?= $reserva["nombre_usuario"] ?></p>
                                <p class="email-usuario"><?= $reserva["email"] ?></p>
                            </div>
                        </div>

                        <div class="contenedor-abajo">

                            <div class="contenedor-extras">
                                <p class="label-extras">EXTRAS</p>
                                <div class="lista-extras">
                                    <?php if (intval($reserva["iluminacion"]) === 1 && intval($reserva["material"]) === 1): ?>
                                        Iluminación + Material
                                    <?php elseif (intval($reserva["iluminacion"]) === 1): ?>
                                        Iluminación
                                    <?php elseif (intval($reserva["material"]) === 1): ?>
                                        Material
                                    <?php endif; ?>

                                </div>

                                <div class="estado-reserva <?= (intval($reserva["pagadas"]) === 1) ? "estado-confirmado" : "estado-tramite" ?>"><?= (intval($reserva["pagadas"]) === 1) ? "Confirmada" : "En trámite" ?></div>
                            </div>

                            <div class="precio-hora-reserva">
                                <?php if(intval($reserva["tipo_reserva"]) === 0) : ?>
                                    <p class="hora-reserva"><?= substr($reserva["hora_inicio"], 0, 5) ?> <span class="duracion-reserva">• 1h</span></p>
                                <?php endif ; ?>
                                <div class="precio-reserva">
                                    <p class="precio-reserva-text"><?= $reserva["precio_pista"] ?>€</p>
                                    <span class="texto-precio">por reserva</span>
                                </div>
                            </div>
                        </div>

                        <div class="card-footer">
                            <button type="button" class="btn btn-danger" id="btn-anular-admin"><i class="bi bi-x-lg"></i>&nbsp;Anular</button>
                            <?= (intval($reserva["pagadas"]) === 1) ? '<button type="button" class="btn btn-secondary" id="btn-deshacer-check-in"><i class="bi bi-arrow-counterclockwise"></i>&nbsp;Deshacer Check-In</button>' : '<button type="button" class="btn btn-success" id="btn-checkIn"><i class="bi bi-check-lg"></i>&nbsp;Check-In</button>' ?>
                        </div>
                    </div>
                    
                </div>
            <?php endforeach; ?>
    
        <?php else : ?>
            <p>No hay reservas de instalaciones para este día</p>
        <?php endif; ?>
    </div>
</div>
                                </div>  

<?= $modalAnularReserva ?>